on: [push, pull_request]

name: CI

jobs:
  generation:
    name: Generation
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt-get install ghdl
          wget https://github.com/apptainer/apptainer/releases/download/v1.2.4/apptainer_1.2.4_amd64.deb -O /tmp/apptainer.deb
          sudo dpkg -i /tmp/apptainer.deb && false
          sudo apt-get install -f
          .github/verilator_apptainer --version

      - name: Setup Python venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python -V
          pip install -r requirements.txt

      - name: Test Generation
        run: |
          export VERILATOR=$(pwd)/.github/verilator_apptainer
          cd proto
          python3 tests.py -e

  interaction:
    name: Interaction
    runs-on: ubuntu-22.04
    steps:
      - name: Install GHDL
        run: sudo apt-get install ghdl

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Python venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python -V
          pip install -r requirements.txt

      - name: Test Generation
        run: |
          cd testfiles/tb
          ./run.sh
